### PR TITLE
Update static B scripts

### PR DESCRIPTION
**Pull request by benjaminmenetrier**
## Description

Update static B training bash scripts for the latest `develop`.

### Issue(s) addressed

None.

## Acceptance Criteria (Definition of Done)

Training working.

## Dependencies

None.

## Impact

None.

### CODE REVIEW

**Comment by benjaminmenetrier** [comment]
To reviewers: I don't expect any testing on your side, but it would be nice to have this PR merged for the B matrix training meeting tomorrow.

**Review by danholdaway — APPROVED** [review]

**Review by shlyaeva — APPROVED** [review]

**Review by climbfuji — COMMENTED** [review]
Should src/Workflows/StaticB/skylab-1.0.0/regrid.sh be renamed to src/Workflows/StaticB/skylab-2.0.0/regrid.sh ?

**Comment by benjaminmenetrier** [comment]
@climbfuji: all the `src/Workflows/StaticB/skylab-1.0.0` scripts were working with the skylab release 1.0.0, and they are still working with release 2.0.0. However, `src/Workflows/StaticB/develop` scripts are now required with the current version of `develop`, which includes refactored SABER blocks. When version 3.0.0 of skylab is released, I'll make a copy of `src/Workflows/StaticB/develop` named `src/Workflows/StaticB/skylab-3.0.0`. 

We could make a copy of `src/Workflows/StaticB/skylab-1.0.0` named `src/Workflows/StaticB/skylab-2.0.0` for completeness. It's only 164K of scripts...

**Comment by benjaminmenetrier** [comment]
Pinging @shlyaeva and @ytremolet to merge this PR.

**Pull request merged**
