### PR TITLE
Static B benchmark

### PR DESCRIPTION
**Pull request by benjaminmenetrier**
## Description

This PR is a minor update to make the scripts suite easier to use. A specific README is added [here](https://github.com/JCSDA-internal/fv3-jedi-tools/tree/feature/benchmark/src/Workflows/StaticB) provide some documentation.

**Last thing to do**: move the background and observations on S3. I was able to upload them in the saber directory, but I don't have the permission to move them into the correct directory:
- `s3://jedi-test-files/saber/bkg_2020121500.tar` should be moved to `s3://fv3-jedi/StaticBTraining/C384/Background/`
- `s3://jedi-test-files/saber/obs.tar` should be moved to `s3://fv3-jedi/StaticBTraining/Observations/`

@mmiesch, @danholdaway, could you do that?

All data for the static B training are stored on S3 in `glacier` mode. Should we "defrost" them for Oak Ridge people?

### Issue(s) addressed

None

## Acceptance Criteria (Definition of Done)

Scripts suite working completely on Orion.

## Dependencies

None.

## Impact

None.

### CODE REVIEW

**Comment by mmiesch** [comment]
Thanks @benjaminmenetrier - when did you upload the background and obs files?  It looks like they have been migrated to glacier and we need to restore them before moving them.   I can start that process but it might take up to a few hours:  
```
$ aws s3 mv s3://jedi-test-files/saber/bkg_2020121500.tar s3://fv3-jedi/StaticBTraining/C384/Background/bkg_2020121500.tar
warning: Skipping file s3://jedi-test-files/saber/bkg_2020121500.tar. Object is of storage class GLACIER. Unable to perform copy operations on GLACIER objects. You must restore the object to be able to perform the operation. See aws s3 copy help for additional parameter options to ignore or force these transfers.
```

**Comment by mmiesch** [comment]
Very strange - I see you just uploaded them today.  I don't know why they went straight to glacier.  I initiated the restore, which could take a few hours.  Later today I will transfer them to the fv3-jedi bucket.

**Comment by benjaminmenetrier** [comment]
@mmiesch: I uploaded the files directly in glacier mode, I didn't know we couldn't transfer them it that state. Sorry!

**Comment by mmiesch** [comment]
> @mmiesch: I uploaded the files directly in glacier mode, I didn't know we couldn't transfer them it that state. Sorry!

No problem - yes, in the future, just uploading them to "standard" mode is best.  The files are inaccessible on glacier - they have to be retrieved before they can be copied to other S3 buckets or externally to HPC systems.  I requested a restore for 30 days.  That should give us some time to transfer them to different systems like Summit for testing.

However - bad news - after returning from vacation, I'm finding most of the saber tests are failing with PGI (they were all passing before my PTO!).  I assume of course that it is due to the big PR.   Oops-related changes are also causing some qg tests to fail.   It may be something minor.  But, in any case, we are no longer ready to test on Summit - I need to debug the new test failures first.

**Pull request merged**
