### PR TITLE
Static B workflow

### PR DESCRIPTION
**Pull request by benjaminmenetrier**
## Description

I developed some bash scripts to run the static B training more efficiently on Orion and deal with dependencies. Basically something like `ewok`... but written in bash.

I think it could be added here, but maybe it's not the relevant place. 

### Issue(s) addressed

None.

## Acceptance Criteria (Definition of Done)

Scripts suite working on Orion.

## Dependencies

Waiting on https://github.com/JCSDA-internal/saber/pull/122.

## Impact

None.

### CODE REVIEW

**Comment by benjaminmenetrier** [comment]
Maybe we could wait for https://github.com/JCSDA-internal/saber/pull/122 to be merged in order to remove the wind variables names in yaml files.

**Review by danholdaway — APPROVED** [review]

**Comment by danholdaway** [comment]
Thanks for adding this here. I think this is the right place until we have a similar functionality in EWOK. And this will be useful for whomever does the development in EWOK to see what the workflow needs to look like.

**Comment by danholdaway** [comment]
Also note that this repo houses the Cylc workflow for converting the cold start ensemble members to psi/chi https://github.com/JCSDA-internal/fv3-jedi-tools/tree/develop/src/Workflows/EMC/ConvertEnsColdStarts_To_BVars

**Comment by fcvdb** [comment]
Thanks Benjamin. This is going to be very useful. I will also let ORNL know about those scripts.

**Comment by benjaminmenetrier** [comment]
If you can just wait a few hours, I'm finishing a minor update for the static B benchmark.

**Pull request merged**
