### PR TITLE
Ferret with raster.py

### LINKED ISSUE #22: Fast plots for FV3 fields
## Description

I'm running experiments with FV3-JEDI at C384 on Orion, but plotting fields with Python using the `src/raster/raster.py` is veeeery slow (more that 4 min for a single variable at a given level).

My question is: would you have scripts to plot FV3 fields faster?
- I checked that loading data is fast, but plotting them is the slow part.
- Python would be great, but I'm open to any other language.
- I can't download data on my own workstation (too slow), I can download figures only.
- I'm using the following environment for Python:
```
export JEDI_OPT=/work/noaa/da/jedipara/opt/modules
module purge
module use $JEDI_OPT/modulefiles/core
module load jedi/gnu-openmpi
module load geos proj
```

Any help would be much appreciated.

### PR DESCRIPTION
**Pull request by benjaminmenetrier**
## Description

This PR introduces `ferret` to plot FV3 fields with `raster.py`, using the `--ferret` option.
It is **a lot faster**: about 9 s instead of several minutes with `matplotlib` for one field at C384 on Orion.
On Orion, `module load ferret` is required and sufficient.

Example at C24:

Matplotlib: `./raster.py --gfs -f ${Data}/20201215.000000.c24.fv_core.res.nc -v T -l 10 -o test`

test_10

Ferret: `./raster.py --gfs -f ${Data}/20201215.000000.c24.fv_core.res.nc -v T -l 10 --ferret -o test_ferret`

test_ferret_10

### Issue(s) addressed

Fixes #22.

## Acceptance Criteria (Definition of Done)

`raster.py` working with `ferret` on Orion.

## Dependencies

None.

## Impact

None.

### CODE REVIEW

**Comment by benjaminmenetrier** [comment]
For reviewers: I'm pinging you to let you know about this new option that can be useful. No need for a full review if you don't have time or don't know ferret well.

**Review by shlyaeva — APPROVED** [review]
I have not reviewed the code (don't know enough to do that). Great to have faster plotting scripts, thank you @benjaminmenetrier.

**Comment by shlyaeva** [comment]
@climbfuji looks like we don't have branch protection rules on this repo because I can merge this PR, and I shouldn't be able to (I don't have access to settings to change that).

**Comment by climbfuji** [comment]
@shlyaeva try again ;-)

**Review by climbfuji — APPROVED** [review]
I know nothing about `ferret`. The Python changes look ok. If time and resources were unlimited I'd suggest polishing the script so that it survives a Python linter, uses logging, etc. As long as this script is for quick and easy visualization for development and testing and not meant for production and dissemination, it's fine as it is now.

I was going to ask Denise Worthen if she wants to take a look at the Ferret side of things, but she can't access the repository ...

**Review by BenjaminRuston — COMMENTED** [review]
OK,, think I got confused.  This still uses cartopy to do the plotting, and adds no additional dependencies.

This looks very good, and would like to use this for plotting increments in model space

**Comment by climbfuji** [comment]
> OK,, think I got confused. This still uses cartopy to do the plotting, and adds no additional dependencies.
> 
> This looks very good, and would like to use this for plotting increments in model space

I read the code as follows:

The command line argument `--ferret` sets the boolean `args.ferret` to `True`, in which case matplotlib and cartopy are not used, not even imported (see the if-then-else statement lines 280 vs 299).

**Comment by benjaminmenetrier** [comment]
Correct!

**Pull request merged**
